### ISSUE TITLE
Unicorn Remote Problems

### ISSUE THREAD

**Issue by Tr33x0rs** [njbbaer/unicorn-remote#9]
I followed your instructions for your unicorn-remote and when running the command to start the program, i get the following error. I did try doing what it suggested with "sudo pip install numpy" but it says it was already installed. Any ideas? Thank you!

sudo pipenv run python run.py 
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/unicorn-remote-QVlOwlcP/lib/python3.5/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/unicorn-remote-QVlOwlcP/lib/python3.5/site-packages/unicornhathd/__init__.py", line 13, in <module>
    import numpy
  File "/root/.local/share/virtualenvs/unicorn-remote-QVlOwlcP/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/root/.local/share/virtualenvs/unicorn-remote-QVlOwlcP/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/root/.local/share/virtualenvs/unicorn-remote-QVlOwlcP/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/root/.local/share/virtualenvs/unicorn-remote-QVlOwlcP/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/root/.local/share/virtualenvs/unicorn-remote-QVlOwlcP/lib/python3.5/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from app import create_app
  File "/home/pi/Pimoroni/unicornhathd/examples/unicorn-remote/app/__init__.py", line 5, in <module>
    from app.state import state
  File "/home/pi/Pimoroni/unicornhathd/examples/unicorn-remote/app/state.py", line 73, in <module>
    state = State()
  File "/home/pi/Pimoroni/unicornhathd/examples/unicorn-remote/app/state.py", line 12, in __init__
    self.set_model(is_hd)
  File "/home/pi/Pimoroni/unicornhathd/examples/unicorn-remote/app/state.py", line 18, in set_model
    import unicornhathd
  File "/root/.local/share/virtualenvs/unicorn-remote-QVlOwlcP/lib/python3.5/site-packages/unicornhathd/__init__.py", line 15, in <module>
    raise ImportError("This library requires the numpy module\nInstall with: sudo pip install numpy")
ImportError: This library requires the numpy module
Install with: sudo pip install numpy

**Comment by njbbaer** [comment]
Hi @Tr33x0rs! Thanks for making an issue. It appears you are missing a dependency numpy relies on.

Try running this:
`sudo apt-get install libatlas-base-dev`
and let me know if that fixes it for you.

**Comment by njbbaer** [comment]
Closing this issue assuming that worked.
